title: Challenge Run Community
description: "Tracking challenge runs, deathless runs, and no-hit achievements across games"
url: https://challengerun.net
markdown: kramdown

# For RSS feed
author: Challenge Run Community

collections:
  games:
    output: true
    permalink: /games/:name/
  runners:
    output: true
    permalink: /runners/:name/
  runs:
    output: false

# Posts are built-in, but we set defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: runs
    values:
      layout: null
      verified: false
  - scope:
      path: ""
      type: games
    values:
      layout: game

exclude:
  - _queue_runs
  - _queue_games
  - _templates
  - scripts
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - .lighthouserc.json
  - README.md
  - LICENSE
  - .docs
  - .github
