title: Challenge Run Community
url: https://challengerun.net
markdown: kramdown

collections:
  games:
    output: true
    permalink: /games/:name/
  runners:
    output: true
    permalink: /runners/:name/
  runs:
    output: false

defaults:
  - scope:
      path: ""
      type: runs
    values:
      layout: null
      verified: false
  - scope:
      path: ""
      type: games
    values:
      layout: game

exclude:
  - _queue_runs
  - _queue_games
  - _templates
  - scripts
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - .lighthouserc.json
  - README.md
  - LICENSE
  - .docs
  - .github
